name: Node CI/CD
on:   
  push:
    branches: source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
        fetch-depth: 1
    - name: Use Node.js
      uses: actions/setup-node@master
    - name: Yarn install, build
      run: |
        yarn
        yarn global add hexo --prefix ~/.config/yarn/
        cp -rf ownfile/* themes/hexo-theme-material/
        ~/.config/yarn/bin/hexo g
    - name: Upload
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
       cd ./public
       git init
       git config user.name "bot"
       git config user.email "bot@github.com"
       echo "simonsmh.cc" > CNAME
       git add .
       git commit -m "Hexo Pages"
       git push --force --quiet "https://$GITHUB_TOKEN@github.com/simonsmh/simonsmh.github.io.git" HEAD:master
